project:
  type: book

book:
  title: "Data Visualization for Social Scientists"
  subtitle: "Using R!"
  author: "Alfredo Hernandez Sanchez, PhD"
  date: "4/5/2024"
  reader-mode: true
  repo-url: "https://github.com/alhdzsz/dviz_book"
  repo-actions: [issue]
  sidebar: 
    logo: "icon.png"
  chapters:
    - index.qmd
    - intro.qmd
    - ggbasics.qmd
    # - networks.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

